import {
  ImageTypes,
  MessageTypes,
  TotalAddressTypes,
  AddressTypes,
  UserFinalDataTypes,
} from './Transaction';

export interface ChatbotStoreTypes {
  isModalShown: boolean,
  input: boolean,
  messages: Array<IMessage>,
  modalVisible: boolean,
  jibunAddress: string,
  roadAddress: string,
  detailAddress: string,
  totalAddress: TotalAddressTypes,
  cameraModalVisible: boolean,
  isCurrentImage: boolean,
  currentImage: ImageTypes,
  itemImages: Array<ImageTypes>,
  userFinalData: UserFinalDataTypes,
  isSetReservation: boolean,
  confirmAlias: string,
  alias: string,

  toggleModal(): void;
  setModalVisible(): void,
  setInput(): void,
  setMessages(messages: MessageTypes): void,
  setAddress(data: AddressTypes): void,
  setDetailAddress(detailAddress: string): void,
  setTotalAddress(type: string): void,
  setUserFinalData(finalData: UserFinalDataTypes): void,
  addReservation(): Promise<void>,
  toggleIsSetReservation(): void,
  falseIsReservation(): void,
  initAddress(): void,
  setCurrentImage(image: ImageTypes): void,
  initCurrentImage(): void,
  setItemImages(): void,
  removeItemImage(key: string): void,
  setCameraModalVisible(): void,
  setAlias(alias: string): void,
  setConfirmAlias(confirmAlias: string): void,
  initChatbotState(): void,
}
